name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BOT_ID: ${{ secrets.BOT_ID }}


    steps:
      - name: Git checkout
        uses: actions/checkout@v2


      - name: run function.js
        run: node ./assets/js/functions.js





